### ISSUE TITLE
Page layout

### ISSUE THREAD

**Issue by neonfuz** [bismuthsoft/fazeoid#23]
Thinking more about the overall page layout. Doing this brings into question the purpose & scope of this project. Is the purpose to make single instruments? to make songs? to use with a DAW? to use in a DAW (as a VST)? Or is the scope of this project include a mini DAW to show off the synth?

I think even if we don't intend it, to show off the synth we need to some extent to implement a mini DAW.

Of course the knob panel is the central focus. The piano is needed to play notes. We don't yet have a composition section like a song editor, nor a feature like midi input to let that be handled externally.

I came up with this mockup:

![Image](https://user-images.githubusercontent.com/2590830/180842158-e1feca61-4185-4270-ac2c-7c40a425e354.png)

Piano on bottom just makes most sense imo. The idea with the panels is:
Left: static, used for loading & saving presets and or songs.
Right: dynamic, like gimp's tool options section, is dynamic to whatever you're focused on.

The right panel may be pretty useless right now but I think it could be useful if this project expands in scope and we want to add things like a song editor.

**Comment by neonfuz** [comment]
@44100hertz thoughts?

**Comment by neonfuz** [comment]
I was also thinking we need somewhere for global config. 2 options I can think of are the drift fix hack for firefox and showing letters on the piano keys.

**Comment by 44100hertz** [comment]
I'm thinking of adding a piano zoom and showing letters past a certain point.

**Comment by 44100hertz** [comment]
We will do this layout for 0.1

**Comment by neonfuz** [comment]
![Image](https://user-images.githubusercontent.com/2590830/183563590-3d20c0f9-4dcd-4004-bb87-6e02183d4de7.png)

Little update of the mockup now that we've done some development

**Comment by 44100hertz** [comment]
Add presets list on the left

**Comment by 44100hertz** [comment]
What remains?

**Comment by neonfuz** [comment]
I think we're good for 0.1
