### ISSUE TITLE
Redesign visuals

### ISSUE THREAD

**Issue by neonfuz** [bismuthsoft/fazeoid#26]
- [x] better background
- [x] logo on page
- [x] copyright text at bottom
- [x] use Genos font
- [x] title somewhere on page
- [x] better padding in horizontal
- [ ] vertical stretch on mobile (wontfix, 0.2)

**Comment by neonfuz** [comment]
We may want to consider using tailwind. Svelte install instructions:

https://tailwindcss.com/docs/guides/sveltekit

**Comment by 44100hertz** [comment]
I have an SVG knob to integrate

**Comment by neonfuz** [comment]
I did essentially go with a new look with the latest refactor. Maybe we should add a checklist here (in OP) of what's remaining before 0.1

**Comment by 44100hertz** [comment]
Put title in BG
