### ISSUE TITLE
BUG: Piano: keys getting stuck

### ISSUE THREAD

**Issue by neonfuz** [bismuthsoft/fazeoid#28]
Usually when I hit at least 3 keys together, at least one gets stuck playing on chrome

To reproduce:
- Open site in chrom{e,ium}
- Spam keys (press 3+ keys together)

Types of stuck notes fixed:
- [x] Hold key and click
- [x] Events dropped before audio worklet initialized
- [x] key held while input focused
- [x] multi touching a single key
- [ ] Firefox sticks on single tap on page load (from hack initialize?)
- [ ] Firefox sticks on double tap gesture spam around key
- [ ] alt-tab, console, etc (fixable by pressing key again, maybe wontfix)

**Comment by neonfuz** [comment]
Found a method to get keys stuck on firefox:
- press and hold a note on physical keyboard
- click any other key
- when everything is released, the first note will continue to play

**Comment by neonfuz** [comment]
I haven't been able to reproduce keys sticking on the latest prod

**Comment by neonfuz** [comment]
OK so I can still get keys stuck but it's a bit hard to say how to reproduce. I got keys stuck when my computer was lagging a bit, makes me think it may be related to a race condition, possibly key release before the keydown is done processing somehow?

Also, holding a key and alt-tabbing, or clicking a different tab gets keys stuck.

**Comment by 44100hertz** [comment]
Remaining problems:

1. Alt tab, opening console, etc. causes problems.
2. Should add a panic button to just stop all playing notes for cases that can't be helped.

**Comment by neonfuz** [comment]
Another way to get keys stuck: it's pretty easy to get one stuck as the audio worklet is firing up. I think instead of dropping key events we need to queue them up, or at least not fire events that will leave the chip in an inconsistent state.

**Comment by neonfuz** [comment]
And another: hold a key and click a knob to focus the input.

**Comment by neonfuz** [comment]
All documented ways of getting the stuck knob have been fixed besides wontfix issues.

**Comment by neonfuz** [comment]
Testing showed firefox mobile still gets stuck on pressing one key after loading.

Also oxygen os triple touch gestures seemed to interfere with pointerup events

**Comment by 44100hertz** [comment]
The octave selector is now sort of a panic button. Let's figure out what can and cannot be solved here and then move this to backburner.

**Comment by neonfuz** [comment]
Maybe we should name it "silence" instead of panic

**Comment by neonfuz** [comment]
Moving this to 0.2, we should fix firefox touch for that release.
