### ISSUE TITLE
Octave +/-

### ISSUE THREAD

**Issue by 44100hertz** [bismuthsoft/fazeoid#40]

**Comment by 44100hertz** [comment]
Gotta figure out sensible minimum and maximum octave. Should be instrument-level, not global. Should affect keyboard input.

**Comment by 44100hertz** [comment]
I'm going to stick a column to the right of the piano with 3 buttons. +, - octave and panic button.

**Comment by 44100hertz** [comment]
107598b

**Comment by neonfuz** [comment]
cool it works
