### ISSUE TITLE
Portrait UI (Mobile)

### ISSUE THREAD

**Issue by 44100hertz** [bismuthsoft/fazeoid#41]
Acceptance criteria:
- [ ] Piano octave scaling
- [ ] space for global & options panel

**Comment by 44100hertz** [comment]
Problems with mobile UI:

1. The piano is too wide
2. Wasted space on the bottom
3. Controls on the left are obscured

**Comment by 44100hertz** [comment]
Proposal 1 (prototype in figma)

 - Swap rows and columns
 -  2 Octave piano
 - (maybe) 3 Oscillators instead of 4

**Comment by neonfuz** [comment]
@44100hertz added acceptance criteria checklist to OP

**Comment by neonfuz** [comment]
Well we don't have key scaling but we have octave +  / - . And with the space for those keys we essentially have an options bar. We can fit more stuff there if we need to.
