### ISSUE TITLE
Import 0.1 instruments

### ISSUE THREAD

**Issue by 44100hertz** [bismuthsoft/fazeoid#51]
0.1 instruments are gonna have to be converted to 0.2 instead of just failing to load

**Comment by neonfuz** [comment]
@44100hertz I remember we did some work on migration, what's the status of this?

**Comment by 44100hertz** [comment]
I guess this is a future thing. We can close this issue because I'm going to add migration every time a feature is added.

**Comment by neonfuz** [comment]
I think a migration system was the essence of this issue so it's solved.
